"""Contracts owned by Inbox capture."""

from typing import Protocol

from .models import InboxCapture, InboxPage


class InboxCaptureStore(Protocol):
    def claim(self, update_id: int, title: str, created_at: str) -> InboxCapture: ...
    def has_capture(self, update_id: int) -> bool: ...
    def finish(self, update_id: int, status: str, page_url: str = "") -> None: ...
    def set_pending_prompt(self, expires_at: float) -> None: ...
    def has_pending_prompt(self, now_timestamp: float) -> bool: ...
    def claim_pending(
        self, update_id: int, title: str, created_at: str, now_timestamp: float
    ) -> InboxCapture | None: ...
    def clear_pending_prompt(self) -> None: ...
    def recover_inflight(self) -> None: ...


class InboxWriter(Protocol):
    def create(self, title: str) -> InboxPage: ...
