"""Ports owned by the personal weather capability."""

from datetime import date, datetime
from typing import Protocol

from .models import DailyDelivery, DailyForecast


class WeatherForecastProvider(Protocol):
    def forecast(self, city: str, day: date, timezone_name: str) -> DailyForecast: ...


class WeatherRepository(Protocol):
    def get_daily(self, day: date) -> DailyDelivery | None: ...
    def prepare_daily(self, day: date, now: datetime) -> None: ...
    def save_daily_text(self, day: date, text: str, now: datetime) -> None: ...
    def claim_daily(self, day: date, now: datetime) -> bool: ...
    def finish_daily(
        self, day: date, status: str, now: datetime, next_attempt: datetime | None = None
    ) -> None: ...
    def recover_inflight(self) -> None: ...


class WeatherSender(Protocol):
    def send(self, chat_id: str, text: str) -> int: ...
