"""External boundaries required by reminder use cases."""

from datetime import date, datetime
from typing import Protocol

from .models import PersonalReminder, TaskDeadline, TaskDigestSettings


class TaskDeadlineSource(Protocol):
    def tasks(self) -> tuple[TaskDeadline, ...]: ...


class ReminderRepository(Protocol):
    def digest_settings(self, defaults: TaskDigestSettings) -> TaskDigestSettings: ...
    def save_digest_settings(self, settings: TaskDigestSettings) -> None: ...
    def prepare_digest(self, day: date, text: str, now: datetime) -> None: ...
    def skip_digest(self, day: date) -> None: ...
    def digest(self, day: date) -> tuple[str, str, datetime | None] | None: ...
    def claim_digest(self, day: date, now: datetime) -> bool: ...
    def finish_digest(
        self, day: date, status: str, next_attempt: datetime | None = None
    ) -> None: ...
    def create_personal(
        self, update_id: int, text: str, due_at: datetime, created_at: datetime
    ) -> PersonalReminder: ...
    def pending_personal(self, limit: int = 20) -> tuple[PersonalReminder, ...]: ...
    def cancel_personal(self, reminder_id: int) -> bool: ...
    def claim_due_personal(self, now: datetime) -> PersonalReminder | None: ...
    def finish_personal(
        self, reminder_id: int, status: str, next_attempt: datetime | None = None
    ) -> None: ...
    def recover_inflight(self) -> None: ...


class ReminderSender(Protocol):
    def send(self, chat_id: str, text: str, *, parse_mode: str | None = None) -> int: ...
